#!/bin/bash

#set -x

res1=$(date +%s.%N)

# Set vars
GIT_ROOT=$(git rev-parse --show-toplevel)
BINARY_DIR="$1"
WD="$BINARY_DIR/experiment"

# Go to working dir
mkdir -p "$WD"
cd "$WD"

# Remove existing simulation results
rm -rf ./*

# Experiments
ARGOS_IN="$GIT_ROOT/src/argos/swarmlist_sim.argos"
FINAL_RES_CSV="$WD/res.csv"
BEHAVIOR_EXECUTABLE="$BINARY_DIR/behaviors/swarmlist_list_based"
KILOBOT_META_STUFF_DELAY=1000
CHECK_IF_FINISHED_DELAY=500
NUM_EXPERIMENTS=5

for topology in line # TODO Add more topologies
do
    for num_robots in 1000 #{10..20..10}
    do
        for msg_drop_prob in 0.00 #0.25 0.50 0.75
        do
            i=1
            while [ $i -le $NUM_EXPERIMENTS ]; do
                experiment_basedir="$WD/exp_${topology}Topology_${num_robots}Robots_${msg_drop_prob}MsgDropProb"
                mkdir -p "$experiment_basedir"

                # Run experiment
                qsub -F "$ARGOS_IN $BEHAVIOR_EXECUTABLE $experiment_basedir \
                $KILOBOT_META_STUFF_DELAY $CHECK_IF_FINISHED_DELAY $NUM_EXPERIMENTS \
                $topology $num_robots $msg_drop_prob \
                ${i}" $GIT_ROOT/src/experimenters/runners/job_runner

                i=$(($i+1))
            done
        done
    done
done

# Concatenate smaller result CSV files into a single one.
RESULT_CSV_FILES=$(find -type f -name "res.csv" | sort -z)
echo -n "Topology,Number of robots,Message drop probability,Consensus time (timesteps),Messages sent (total),Messages received (total),Avg. bandwidth (B/(timestep*kilobot)),Avg. received bandwidth (B/(timestep*kilobot))" > $FINAL_RES_CSV
for res in $RESULT_CSV_FILES
do
    cat $res | tail -n +1 >> $FINAL_RES_CSV
done

# Echo time taken

res2=$(date +%s.%N)
dt=$(echo "$res2 - $res1" | bc)
dd=$(echo "$dt/86400" | bc)
dt2=$(echo "$dt-86400*$dd" | bc)
dh=$(echo "$dt2/3600" | bc)
dt3=$(echo "$dt2-3600*$dh" | bc)
dm=$(echo "$dt3/60" | bc)
ds=$(echo "$dt3-60*$dm" | bc)

printf "Total runtime: %d:%02d:%02d:%02.4f\n" $dd $dh $dm $ds
